=== GitAlishev/ITMO_labs/CS/xml/document.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="Schedule">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="worker" maxOccurs="unbounded" minOccurs="0">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:element name="name">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="surname"/>
                                        <xs:element type="xs:string" name="initials"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="job"/>
                            <xs:element name="work_hours" maxOccurs="unbounded" minOccurs="0">
                                <xs:complexType>
                                    <xs:sequence>
                                        <xs:element type="xs:string" name="mon" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element type="xs:string" name="tue" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element type="xs:string" name="wed" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element type="xs:string" name="thu" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element type="xs:string" name="fri" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element type="xs:string" name="time" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element type="xs:string" name="sat" minOccurs="0" maxOccurs="unbounded"/>
                                        <xs:element type="xs:string" name="time_sat" minOccurs="0" maxOccurs="unbounded"/>
                                    </xs:sequence>
                                </xs:complexType>
                            </xs:element>
                            <xs:element type="xs:string" name="notes" minOccurs="0"/>
                        </xs:sequence>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>

=== GitAlishev/ITMO_labs/Computer Science/xml/documentXSD_XSL.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type='text/xsl' href='document.xsl'?>
<Schedule
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:noNamespaceSchemaLocation="document.xsd"
>
    <worker>
	    <name>
	        <surname>Иванов </surname>
	        <initials>Д.Н.</initials>
	    </name>
	    <job>Должность: Продавец</job>
	    <work_hours>
	        <mon>ПН, 6.11</mon>
	        <time>10:00 - 17:00</time>
	    </work_hours>
	    <work_hours>
	        <tue>ВТ, 7.11</tue>
	        <time>10:00 - 17:00</time>
	    </work_hours>
	    <work_hours>
	        <wed>СР, 8.11</wed>
	        <time>10:00 - 17:00</time>
	    </work_hours>
	    <work_hours>
	        <thu>ЧТ, 9.11</thu>
	        <time>10:00 - 17:00</time>
	    </work_hours>
	    <work_hours>
	        <fri>ПТ, 10.11</fri>
	        <time>10:00 - 17:00</time>
	    </work_hours>
	    <work_hours>
	        <sat>СБ, 11.11</sat>
	        <time_sat>10:00 - 15:00</time_sat>
	    </work_hours>
	    <notes>Примечания: День рождения - 1 февраля 1980</notes>
	</worker>
	<worker>
	    <name>
	        <surname>Фахриев </surname>
	        <initials>Д.Р.</initials>
	    </name>
	    <job>Должность: Инженер</job>
	    <work_hours>
	        <mon>ПН, 6.11</mon>
	        <time>12:00 - 19:00</time>
	    </work_hours>
	    <work_hours>
	        <tue>ВТ, 7.11</tue>
	        <time>12:00 - 19:00</time>
	    </work_hours>
	    <work_hours>
	        <wed>СР, 8.11</wed>
	        <time>12:00 - 19:00</time>
	    </work_hours>
	    <work_hours>
	        <thu>ЧТ, 9.11</thu>
	        <time>12:00 - 19:00</time>
	    </work_hours>
	    <work_hours>
	        <fri>ПТ, 10.11</fri>
	        <time>12:00 - 19:00</time>
	    </work_hours>
	    <work_hours>
	        <sat>СБ, 11.11</sat>
	        <time_sat>15:00 - 20:00</time_sat>
	    </work_hours>
	    <notes>Примечания: День рождения - 5 февраля 1976</notes>
	</worker>
	<worker>
	    <name>
	        <surname>Захаревич </surname>
	        <initials>Н.Р.</initials>
	    </name>
	    <job>Должность: Аналитик</job>
	    <work_hours>
	        <mon>ПН, 6.11</mon>
	        <time>10:00 - 18:00</time>
	    </work_hours>
	    <work_hours>
	        <tue>ВТ, 7.11</tue>
	        <time>12:00 - 19:00</time>
	    </work_hours>
	    <work_hours>
	        <wed>СР, 8.11</wed>
	        <time>12:00 - 19:00</time>
	    </work_hours>
	    <work_hours>
	        <thu>ЧТ, 9.11</thu>
	        <time>12:00 - 19:00</time>
	    </work_hours>
	    <work_hours>
	        <fri>ПТ, 10.11</fri>
	        <time>12:00 - 19:00</time>
	    </work_hours>
	    <work_hours>
	        <sat>СБ, 11.11</sat>
	        <time_sat>16:00 - 20:00</time_sat>
	    </work_hours>
	    <notes>Примечания: День рождения - 7 ноября 1984</notes>
	</worker>
</Schedule>
